// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WidgetsApp.Models;

namespace WidgetsApp.Migrations
{
    [DbContext(typeof(WidgetsContext))]
    partial class WidgetsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("WidgetsApp.Models.Widget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.HasKey("Id");

                    b.ToTable("Widgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "red",
                            Name = "Red Widget",
                            Quantity = 23
                        },
                        new
                        {
                            Id = 2,
                            Color = "blue",
                            Name = "Blue Widget",
                            Quantity = 31
                        },
                        new
                        {
                            Id = 3,
                            Color = "yellow",
                            Name = "Yellow Widget",
                            Quantity = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
